-- MySQL Script generated by MySQL Workbench
-- Sun May 19 12:05:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fcio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fcio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fcio` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `fcio` ;

-- -----------------------------------------------------
-- Table `fcio`.`fundation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcio`.`fundation` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(1000) NOT NULL,
  `vision` TEXT NOT NULL,
  `mision` TEXT NOT NULL,
  `history` TEXT NOT NULL,
  `infoIdiomas` TEXT NOT NULL,
  `idioma` TINYINT NOT NULL,
  `creationDateTime` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fcio`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcio`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  `newsletter` TINYINT NOT NULL,
  `creationDateTime` DATETIME NOT NULL,
  `fundation` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_fundation1_idx` (`fundation` ASC) VISIBLE,
  CONSTRAINT `fk_user_fundation1`
    FOREIGN KEY (`fundation`)
    REFERENCES `fcio`.`fundation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fcio`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcio`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `name` VARCHAR(1000) NOT NULL,
  `text` TEXT NOT NULL,
  `image` VARCHAR(1000) NOT NULL,
  `creationDateTime` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `post_user`
    FOREIGN KEY (`user`)
    REFERENCES `fcio`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fcio`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcio`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `post` INT NOT NULL,
  `text` VARCHAR(1000) NOT NULL,
  `creationDateTime` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `comment_user_idx` (`user` ASC) VISIBLE,
  INDEX `fk_comment_post1_idx` (`post` ASC) VISIBLE,
  CONSTRAINT `comment_user`
    FOREIGN KEY (`user`)
    REFERENCES `fcio`.`user` (`id`),
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post`)
    REFERENCES `fcio`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fcio`.`community`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcio`.`community` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `text` TEXT NOT NULL,
  `tribe` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fcio`.`donationcampaign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcio`.`donationcampaign` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `community` SMALLINT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `text` TEXT NOT NULL,
  `creationDateTime` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `DonationCampaign_community_idx` (`community` ASC) VISIBLE,
  CONSTRAINT `DonationCampaign_community`
    FOREIGN KEY (`community`)
    REFERENCES `fcio`.`community` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fcio`.`donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcio`.`donation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `campaign` SMALLINT NULL,
  `details` VARCHAR(1000) NOT NULL,
  `dateTime` DATETIME NOT NULL,
  `approved` TINYINT NOT NULL,
  `approvalDateTime` DATETIME NULL,
  `approvedBy` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `donation_campaign_idx` (`campaign` ASC) VISIBLE,
  INDEX `donation_approvedBy_idx` (`approvedBy` ASC) VISIBLE,
  INDEX `donation_user_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `donation_approvedBy`
    FOREIGN KEY (`approvedBy`)
    REFERENCES `fcio`.`user` (`id`),
  CONSTRAINT `donation_campaign`
    FOREIGN KEY (`campaign`)
    REFERENCES `fcio`.`donationcampaign` (`id`),
  CONSTRAINT `donation_user`
    FOREIGN KEY (`user`)
    REFERENCES `fcio`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fcio`.`slide`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcio`.`slide` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `community` SMALLINT NOT NULL,
  `image` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_slide_community1_idx` (`community` ASC) VISIBLE,
  CONSTRAINT `fk_slide_community1`
    FOREIGN KEY (`community`)
    REFERENCES `fcio`.`community` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fcio`.`visitlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fcio`.`visitlog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `community` SMALLINT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `details` VARCHAR(1000) NOT NULL,
  `dateTime` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `visitLog_user_idx` (`user` ASC) VISIBLE,
  INDEX `visitLog_community_idx` (`community` ASC) VISIBLE,
  CONSTRAINT `visitLog_community`
    FOREIGN KEY (`community`)
    REFERENCES `fcio`.`community` (`id`),
  CONSTRAINT `visitLog_user`
    FOREIGN KEY (`user`)
    REFERENCES `fcio`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
