@api = http://localhost:4000/api/fundacion

GET {{api}}/1

###

PATCH {{api}}/1
Content-Type: application/json

{
    "vision": "La Casa del Indio es una Organización no gubernamental que se enfoca en brindarle hogar a indígenas de diferentes zonas del país para que estos tengan hogar en caso de que tengan que visitar Cartago o cercanìas, entre otros tipos de ayuda que se les puedes ofrecer a esta parte de la población.",
    "history": "Historia de la Fundacion"
}