@api = http://localhost:4000/api/post

GET {{api}}

###

GET {{api}}/1

###

POST {{api}}
Content-Type: application/json

{
    "user": 2,
    "name": "Post Prueba",
    "text": "Este es un post de prueba creado con el API.",
    "image": "./Card1.png"
}

###

DELETE {{api}}/2

###

PATCH {{api}}/2
Content-Type: application/json

{
    "user": 2,
    "name": "Post Prueba UPDATE",
    "text": "Este es un post de prueba creado con el API y actualizado con el UPDATE.",
    "image": "./Card1.png"
}